# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27b1e3c6b3dc8bd552a11a9a6f0bc7ea216b0e87b52d7624642dfcea89d791d0285f1c19468baba41575dc47e695455c63ba2411ef2865f3d809b147c9c7f0e1

test:
  secret_key_base: 7288e9ff3080ddc5fe1a53da13a7f70ac54ded80647650658ed5f9552979436f16f74389a1d612ff720e05bc0ff75471e10ce3d38bdb533aa9ae249d9c055d25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
